In [125]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 964926347732827968
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 3225408314893130053
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 13804827996640473845
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15956161332
locality {
  bus_id: 1
  links {
  }
}
incarnation: 12067914164712434704
physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"
]


In [0]:
import pandas as pd

In [0]:
#loading the training data
train_df=pd.read_csv('/content/train.csv',encoding='utf-8')

In [0]:
#making 2 lists of tweets and correspong sentiments
tweets=list(train_df['Tweet'])
sentiments=list(train_df['Sentiment'])
sentiments

In [0]:
from nltk import FreqDist
fd=dict(FreqDist(sentiments))
fd

{'negative': 4456, 'neutral': 5631, 'positive': 5030}

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
senti=sentiments.copy()

In [0]:
#converting the string labels to integer representations
enc=LabelEncoder()
enc.fit(sentiments)
sentiments_new=enc.transform(sentiments)
sentiments_new

array([0, 2, 2, ..., 0, 0, 0])

In [0]:
tweets

In [0]:
import keras

Using TensorFlow backend.


In [0]:
tokenizer=keras.preprocessing.text.Tokenizer(filters='',lower=False)

In [0]:
# Creates a word to index mapping of every word
tokenizer.fit_on_texts(tweets)

In [0]:
#converts the tweets to sequences of integer representations
tweets = tokenizer.texts_to_sequences(tweets )

In [0]:
# padding all tweets to length of 60
from keras.preprocessing.sequence import pad_sequences
tweets=pad_sequences(tweets,maxlen=60,padding='post')

In [0]:
tweets

In [0]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

53817

In [0]:
len(tweets)

15117

In [0]:
from numpy import array
from keras.utils import to_categorical
tweets = array(tweets)
    

In [0]:
tweets.shape

(15117, 60)

In [0]:
X=tweets
y=sentiments_new

In [0]:
#assigning weights to classes
from sklearn.utils import compute_class_weight
import numpy as np
classWeight = compute_class_weight('balanced', np.unique(y), y) 
classWeight = dict(enumerate(classWeight))

In [0]:
y

In [0]:
seq_length = X.shape[1] 

In [126]:
from keras.models import Sequential, Model
from keras.layers import Dense, BatchNormalization,Embedding
from keras.layers import LSTM, Input, Bidirectional,CuDNNLSTM,CuDNNGRU
# model architecture
model = Sequential()
model.add(Embedding(vocab_size, 50,input_length=seq_length,trainable=True)) 
model.add((CuDNNGRU(60)))
model.add(BatchNormalization())
model.add(Dense(3, activation='softmax'))
print(model.summary())

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_20 (Embedding)     (None, 60, 50)            2690850   
_________________________________________________________________
cu_dnngru_11 (CuDNNGRU)      (None, 60)                20160     
_________________________________________________________________
batch_normalization_13 (Batc (None, 60)                240       
_________________________________________________________________
dense_22 (Dense)             (None, 3)                 183       
Total params: 2,711,433
Trainable params: 2,711,313
Non-trainable params: 120
_________________________________________________________________
None


In [127]:
from keras import optimizers
# compile model with adam optimizer, sparse categorical cross entropy
model.compile(loss='sparse_categorical_crossentropy', optimizer=keras.optimizers.Adam(lr=0.0001), metrics=['accuracy']) #categorical crossentropy as there are multiple classes of words to predict
model_history=model.fit(X, y, batch_size=10, epochs=20,validation_split=0.01,class_weight=classWeight)

Train on 14965 samples, validate on 152 samples
Epoch 1/20
14965/14965 [==============================] - 14s 954us/step - loss: 1.0971 - acc: 0.3447 - val_loss: 1.1961 - val_acc: 1.0000
Epoch 2/20
14965/14965 [==============================] - 11s 736us/step - loss: 1.0971 - acc: 0.3496 - val_loss: 1.2798 - val_acc: 0.0000e+00
Epoch 3/20
14965/14965 [==============================] - 11s 748us/step - loss: 1.0971 - acc: 0.3641 - val_loss: 1.3695 - val_acc: 0.0000e+00
Epoch 4/20
14965/14965 [==============================] - 11s 746us/step - loss: 0.9850 - acc: 0.4665 - val_loss: 1.5992 - val_acc: 0.3684
Epoch 5/20
14965/14965 [==============================] - 11s 730us/step - loss: 0.7891 - acc: 0.6154 - val_loss: 0.3892 - val_acc: 0.9079
Epoch 6/20
14965/14965 [==============================] - 11s 736us/step - loss: 0.6435 - acc: 0.7046 - val_loss: 2.1294 - val_acc: 0.2566
Epoch 7/20
14965/14965 [==============================] - 11s 724us/step - loss: 0.5290 - acc: 0.7705 - val_lo

In [0]:
#load test data
test=pd.read_csv('/content/test.csv',encoding='utf-8')
test.Tweet=test.Tweet.astype(str)

In [0]:
#lists of test tweets and labels
test_tweets=list(test['Tweet'])
test_y=list(test['Sentiment'])
test_tweets

In [0]:
#convert labels to integers
test_new=enc.transform(test_y)

In [0]:
test_tweets

In [0]:
#convert tweets to sequences of integers
test_tweets= tokenizer.texts_to_sequences(test_tweets )

In [0]:
#pad tweets to length 60
X_test=pad_sequences(test_tweets,maxlen=60,padding='post')

In [0]:
y_test=test_new
np.unique(y_test)

array([0, 1, 2])

In [128]:
#test the model
model.evaluate(X_test,y_test,batch_size=10)

1869/1869 [==============================] - 1s 285us/step


[2.3831745809519145, 0.5098983476894179]

In [0]:
#getting predictions to get recall, etc
y_pred=model.predict_classes(X_test)

In [0]:
y_pred

array([2, 2, 0, ..., 0, 0, 0])

In [0]:
enc.inverse_transform([0,1,2])

array(['negative', 'neutral', 'positive'], dtype='<U8')

In [131]:
#getting F1 Score, Recall, precision
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.56      0.46      0.50       533
           1       0.46      0.57      0.51       754
           2       0.55      0.48      0.51       582

    accuracy                           0.51      1869
   macro avg       0.52      0.50      0.51      1869
weighted avg       0.52      0.51      0.51      1869

